START TRANSACTION;



ALTER TABLE "Vjsf" ADD "BackGroundColor" text NULL;

ALTER TABLE "Vjsf" ADD "Font" text NULL;

ALTER TABLE "Vjsf" ADD "ForeColor" text NULL;

ALTER TABLE "Vjsf" ADD "NextButtonText" text NULL;

ALTER TABLE "Vjsf" ADD "PrevButtonText" text NULL;


INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230912023648_AddFields', '7.0.5');

COMMIT;



ALTER TABLE IF EXISTS public."Questionnaire"
    RENAME "Name" TO "Text";


ALTER TABLE IF EXISTS public."Questionnaire"
    RENAME "Code" TO "Name";



START TRANSACTION;

DROP INDEX "IX_user_email";

CREATE UNIQUE INDEX "IX_user_email" ON "Users" ("Email");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230930034715_AddUserIndex', '7.0.11');

COMMIT;


START TRANSACTION;

ALTER TABLE "Questionnaire" ADD "Enabled" boolean NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20231007025500_AddEnabledField', '7.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "Vjsf" ADD "NextQuestionCondition" text NULL;

ALTER TABLE "Vjsf" ADD "ShowNexButton" boolean NOT NULL DEFAULT TRUE;

CREATE TABLE "QuestionImage" (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    "QuestionId" integer NULL,
    "Name" text NULL,
    "Path" text NULL,
    "CssStyle" text NULL,
    CONSTRAINT "PK_QuestionImage" PRIMARY KEY (id)
);

CREATE UNIQUE INDEX ix_question_image ON "QuestionImage" ("Name");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20231007061852_QuestionImage', '7.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "Vjsf" ADD "ShowPrevButton" boolean NOT NULL DEFAULT TRUE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20231007095358_AddShowPrevButton', '7.0.11');

COMMIT;



START TRANSACTION;

CREATE TABLE "AnswerNote" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "AnswerId" integer NULL,
    "Note" text NULL,
    "LUser" integer NULL,
    "CUser" integer NULL,
    "Ldate" timestamp without time zone NULL,
    "Cdate" timestamp without time zone NULL,
    CONSTRAINT "PK_AnswerNote" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX ix_answer_note_answer_id ON "AnswerNote" ("AnswerId");

GRANT ALL ON TABLE public."AnswerNote" TO postgres;

GRANT DELETE, UPDATE, INSERT, SELECT ON TABLE public."AnswerNote" TO "user";


--CREATE TABLE v_answer2 (
--    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
--    "QuestionnarieId" integer NULL,
--    "UserName" text NULL,
--    "UserEmail" text NULL,
--    "UserPhone" text NULL,
--    "Cdate" date NULL,
--    "SessionId" text NULL,
--    "Time" text NULL,
--    "Os" text NULL,
--    "Area" text NULL,
--    "Browser" text NULL,
--    "ScreenSize" text NULL,
--    CONSTRAINT "PK_v_answer2" PRIMARY KEY ("Id")
--);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240201024059_AnsverNote', '7.0.11');

COMMIT;