START TRANSACTION;



ALTER TABLE "Vjsf" ADD "BackGroundColor" text NULL;

ALTER TABLE "Vjsf" ADD "Font" text NULL;

ALTER TABLE "Vjsf" ADD "ForeColor" text NULL;

ALTER TABLE "Vjsf" ADD "NextButtonText" text NULL;

ALTER TABLE "Vjsf" ADD "PrevButtonText" text NULL;


INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230912023648_AddFields', '7.0.5');

COMMIT;



ALTER TABLE IF EXISTS public."Questionnaire"
    RENAME "Name" TO "Text";


ALTER TABLE IF EXISTS public."Questionnaire"
    RENAME "Code" TO "Name";



START TRANSACTION;

DROP INDEX "IX_user_email";

CREATE UNIQUE INDEX "IX_user_email" ON "Users" ("Email");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230930034715_AddUserIndex', '7.0.11');

COMMIT;


START TRANSACTION;

ALTER TABLE "Questionnaire" ADD "Enabled" boolean NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20231007025500_AddEnabledField', '7.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "Vjsf" ADD "NextQuestionCondition" text NULL;

ALTER TABLE "Vjsf" ADD "ShowNexButton" boolean NOT NULL DEFAULT TRUE;

CREATE TABLE "QuestionImage" (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    "QuestionId" integer NULL,
    "Name" text NULL,
    "Path" text NULL,
    "CssStyle" text NULL,
    CONSTRAINT "PK_QuestionImage" PRIMARY KEY (id)
);

CREATE UNIQUE INDEX ix_question_image ON "QuestionImage" ("Name");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20231007061852_QuestionImage', '7.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "Vjsf" ADD "ShowPrevButton" boolean NOT NULL DEFAULT TRUE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20231007095358_AddShowPrevButton', '7.0.11');

COMMIT;